version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:rw
    env_file:
      - ./.env

  mysql:
    build:
      context: .
      dockerfile: dockerfiles/mysql.dockerfile
    env_file:
      - ./.env

  ### Utilities ###

  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/artisan.dockerfile
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./.env
    entrypoint: ["php", "/var/www/html/artisan"]