---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: gintarassova/php-ldk:latest
          imagePullPolicy: Always
          env:
            - name: APACHE_DOCUMENT_ROOT
              value: /var/www/html/public
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mysql-service.default
            - name: DB_DATABASE
              value: homestead
            - name: DB_USERNAME
              value: homestead
            - name: DB_PASSWORD
              value: secret
          ports:
            - containerPort: 80
      initContainers:
        - name: artisan
          image: gintarassova/artisan-ldk:latest
          imagePullPolicy: Always
          command: ["sh", "-c", "(php artisan migrate || true) && (php artisan config:cache || true) && (php artisan route:cache || true)"]
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mysql-service.default
            - name: DB_DATABASE
              value: homestead
            - name: DB_USERNAME
              value: homestead
            - name: DB_PASSWORD
              value: secret